import { AgeRange } from '../data/tax-config';

/**
 * User options for tax calculation.
 */
export interface UserOptions {
  /** Age range for pension contribution calculation */
  ageRange: AgeRange;
  /** Municipal tax rate (percentage) */
  municipalityRate: number;
  /** Whether user is a church member */
  churchMember: boolean;
}

/**
 * Input parameters for salary calculation.
 */
export interface SalaryInput {
  /** Gross monthly salary in EUR */
  grossMonthlySalary: number;
  /** Yearly bonus in EUR (optional, defaults to 0) */
  yearlyBonus: number;
}

/**
 * Detailed breakdown of all tax and contribution components.
 * All values are monthly amounts in EUR.
 */
export interface TaxBreakdown {
  /** State income tax (monthly) */
  stateTax: number;
  /** Municipal income tax (monthly) */
  municipalTax: number;
  /** Church tax (monthly, 0 if not a member) */
  churchTax: number;
  /** Pension contribution TyEL (monthly) */
  pensionContribution: number;
  /** Unemployment insurance contribution (monthly) */
  unemploymentContribution: number;
  /** Health insurance contribution (monthly) */
  healthInsurance: number;
  /** Work income credit applied (monthly, reduces taxes) */
  workIncomeCredit: number;
  /** Total deductions before work income credit */
  grossDeductions: number;
  /** Total deductions after work income credit */
  totalDeductions: number;
}

/**
 * Result of a salary calculation.
 */
export interface CalculationResult {
  /** Gross monthly salary (input) */
  grossMonthly: number;
  /** Yearly bonus amount (input) */
  yearlyBonus: number;
  /** Calculated yearly gross income */
  grossYearly: number;
  /** Detailed breakdown of all deductions */
  breakdown: TaxBreakdown;
  /** Effective total tax/deduction rate as percentage */
  effectiveTaxRate: number;
  /** Total monthly deductions (same as breakdown.totalDeductions) */
  monthlyTaxPaid: number;
  /** Net monthly salary after all deductions */
  netMonthlySalary: number;
  /** Net yearly salary after all deductions */
  netYearlySalary: number;
}

/**
 * A saved calculation with metadata.
 */
export interface SavedCalculation extends CalculationResult {
  /** Unique identifier (auto-generated by database) */
  id?: number;
  /** User-provided name for this calculation */
  name: string;
  /** Timestamp when calculation was saved */
  createdAt: Date;
  /** User options used for this calculation */
  userOptions?: UserOptions;
}

/**
 * Legacy TaxBracket interface (kept for backwards compatibility during migration).
 * @deprecated Use StateTaxBracket from tax-config.ts instead
 */
export interface TaxBracket {
  /** Minimum yearly salary for this bracket (inclusive) */
  minSalary: number;
  /** Maximum yearly salary for this bracket (inclusive) */
  maxSalary: number;
  /** Tax rate percentage (e.g., 25.5 means 25.5%) */
  taxRate: number;
}
